version: 2

updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /src/cyclo/vendor_gateway/gateway_context
    schedule:
      interval: weekly
      day: monday
    groups:
      gateway-node-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /src/cyclo/vendor_gateway/runtime_context
    schedule:
      interval: weekly
      day: monday
    groups:
      runtime-node-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: docker
    directory: /src/cyclo/vendor_gateway/runtime_context
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: docker
    directory: /src/cyclo/vendor_gateway/gateway_context
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 3

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      github-actions:
        patterns:
          - "*"
    open-pull-requests-limit: 5
